builders:
  safe_json_serializable:
    import: "package:safe_json_serializable/safe_json_serializable.dart"
    builder_factories: ["safeJsonSerializable"]
    build_extensions: { ".dart": ["json_serializable.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
